[window]
decorations = "full"
dynamic_padding = true
opacity = 1

[window.dimensions]
columns = 204
lines = 52

[window.padding]
x = 10
y = 10

# To render colors correctly when using tmux.
[env]
TERM = "alacritty-direct"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 15

### Font Used: Cascadia Code (Mono) ###
[font.bold]
family = "Cascadia Mono"
style = "Bold"

[font.bold_italic]
family = "Cascadia Mono"
style = "Bold Italic"

[font.italic]
family = "Cascadia Mono"
style = "Italic"

[font.normal]
family = "Cascadia Mono"
style = "Regular"
### End font ###

### Theme Kanagawa Wave: https://github.com/rebelot/kanagawa.nvim ###
[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[colors.bright]
black = "0x727169"
blue = "0x7fb4ca"
cyan = "0x7aa89f"
green = "0x98bb6c"
magenta = "0x938aa9"
red = "0xe82424"
white = "0xdcd7ba"
yellow = "0xe6c384"

[colors.normal]
black = "0x090618"
blue = "0x7e9cd8"
cyan = "0x6a9589"
green = "0x76946a"
magenta = "0x957fb8"
red = "0xc34043"
white = "0xc8c093"
yellow = "0xc0a36e"

[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"
### End theme ###

